# Generated by Django 4.2.5 on 2023-09-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_address_student_is_graduated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_graduated',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
