# Generated by Django 4.2.5 on 2023-10-16 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_article_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_users',
        ),
    ]
